apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic

spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
      - name: petclinic
        image: ${IMAGE}
        imagePullPolicy: Always

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL

        ports:
        - containerPort: 8080

        env:
        - name: MYSQL_URL
          value: jdbc:mysql://${RDS}:3306/petclinic

        - name: MYSQL_USER
          value: admin

        - name: MYSQL_PASS
          value: admin123!

        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp

      volumes:
      - name: tmp-volume
        emptyDir: {}

